CREATE TABLE USERS(
Password VARCHAR(20) NOT NULL,
Name VARCHAR(20) NOT NULL,
Surname VARCHAR(20) NOT NULL,
Email VARCHAR(50) NOT NULL, --unique
Birthday DATE,
Sex CHAR NOT NULL,
Address1 VARCHAR(50) NOT NULL,
Address2 VARCHAR(50) NOT NULL,
City VARCHAR(15) NOT NULL,
PostalCode INT NOT NULL,
HomeNumber VARCHAR(10) NOT NULL,  --bigint?
PhoneNumber VARCHAR(10) NOT NULL,
Member BINARY NOT NULL,
Country VARCHAR(15) NOT NULL,
DateOfAccountCreation DATE NOT NULL,
CONSTRAINT user_pk PRIMARY KEY (Password)
);

CREATE TABLE ADMINS(
Password VARCHAR(20) NOT NULL,
Email VARCHAR(50) NOT NULL,
CONSTRAINT admin_pk PRIMARY KEY (Password)
);

CREATE TABLE PRODUCT( --image???
Code INT NOT NULL,
Name VARCHAR(20) NOT NULL,
Description VARCHAR(500) NOT NULL,
Price DOUBLE(5,2) NOT NULL,
CodeOfCategory INT NOT NULL,
EntryDate DATE,
CodeOfSupplier INT NOT NULL,
Weight DOUBLE(4,2) NOT NULL,
Availability INT NOT NULL,
CONSTRAINT product_pk PRIMARY KEY (Code),
CONSTRAINT product_category_fk FOREIGN KEY(CodeOfCategory) REFERENCES CATEGORY (Code),
CONSTRAINT product_supplier_fk FOREIGN KEY(CodeOfSupplier) REFERENCES SUPPLIER (SupplierNumber)
);

CREATE TABLE ORDERS(
Code INT NOT NULL,
Password_user VARCHAR(20) NOT NULL, --??
Name VARCHAR(20) NOT NULL,
DateCreated DATE,
Price DOUBLE(5,2) NOT NULL,
Completed BINARY NOT NULL,
Canceled BINARY NOT NULL,
DateSent DATE,
CarrierNumber INT NOT NULL,
ShippingCost DOUBLE(6,2) NOT NULL,
Weight DOUBLE(6,2) NOT NULL,
CONSTRAINT order_pk PRIMARY KEY (Code),
CONSTRAINT order_category_fk FOREIGN KEY(Password_user) REFERENCES USERS(Password),
CONSTRAINT order_carrier_fk FOREIGN KEY(CarrierNumber) REFERENCES CARRIER(CarrierNumber)
);

CREATE TABLE SERIESOFORDERS(
CodeOfOrder INT NOT NULL,
CodeOfProduct INT NOT NULL,
Date_order DATE,
CONSTRAINT series_order_fk FOREIGN KEY(CodeOfOrder) REFERENCES ORDERS(Code),
CONSTRAINT series_product_fk FOREIGN KEY(CodeOfProduct) REFERENCES PRODUCT(Code),
--CONSTRAINT order_pk PRIMARY KEY (Date_order)
);

CREATE TABLE CATEGORY( --IMAGE???
Code INT NOT NULL,
Name VARCHAR(20) NOT NULL,
Description VARCHAR(500) NOT NULL,
CONSTRAINT category_pk PRIMARY KEY (Code)
);

CREATE TABLE SUPPLIER(
SupplierNumber INT NOT NULL,
CompanyName VARCHAR(20) NOT NULL,
Address1 VARCHAR(50) NOT NULL,
Address2 VARCHAR(50) NOT NULL,
City VARCHAR(15) NOT NULL,
PostalCode INT NOT NULL,
TelephoneNumber VARCHAR(10) NOT NULL,
Email VARCHAR(50) NOT NULL,
Site VARCHAR(50) NOT NULL,
Fax VARCHAR(10) NOT NULL,
CONSTRAINT supplier_pk PRIMARY KEY (SupplierNumber)
);

CREATE TABLE CARRIER(
CarrierNumber INT NOT NULL,
CompanyName VARCHAR(20) NOT NULL, 
TelephoneNumber VARCHAR(10) NOT NULL,
PricePerkg DOUBLE(5,2) NOT NULL,
CostperkmInOtherCountries DOUBLE(5,2) NOT NULL,
CostperkmInCyprus DOUBLE(5,2) NOT NULL,
DaysOfDelivery VARCHAR(15) NOT NULL,
CONSTRAINT carrier_pk PRIMARY KEY (CarrierNumber)
);

CREATE TABLE USERACTIONFORCART(
UserCode VARCHAR(20) NOT NULL,
CodeOfProduct INT NOT NULL,
CONSTRAINT action_user_fk FOREIGN KEY(UserCode) REFERENCES USERS(Password),
CONSTRAINT action_product_fk FOREIGN KEY(CodeOfProduct) REFERENCES PRODUCT(Code)
);

CREATE TABLE VIEWPRODUCT(
UserCode VARCHAR(20) NOT NULL,
CodeOfProduct INT NOT NULL,
Date_view DATE,
SumTimes INT NOT NULL,
--CONSTRAINT view_pk PRIMARY KEY (Date_profile),
CONSTRAINT view_product_fk FOREIGN KEY(CodeOfProduct) REFERENCES PRODUCT(Code),
CONSTRAINT view_user_fk FOREIGN KEY(UserCode) REFERENCES USERS(Password)
);

CREATE TABLE USERPROFILECHANGE(
UserCode VARCHAR(20) NOT NULL,
Date_profile DATE,
FieldChanged VARCHAR(50) NOT NULL,
LastValue VARCHAR(50) NOT NULL,
NewValue VARCHAR(50) NOT NULL,
--CONSTRAINT profile_pk PRIMARY KEY (Date_profile),
CONSTRAINT profile_user_fk FOREIGN KEY(UserCode) REFERENCES USERS(Password)
);

CREATE TABLE PRODUCTCHANGED(
AdministratorID VARCHAR(20) NOT NULL,
CodeOfProduct INT NOT NULL,
Date_change DATE,
FieldChanged VARCHAR(50) NOT NULL,
LastValue VARCHAR(50) NOT NULL,
NewValue VARCHAR(50) NOT NULL,
--CONSTRAINT profile_pk PRIMARY KEY (Date_change),
CONSTRAINT change_product_fk FOREIGN KEY(CodeOfProduct) REFERENCES PRODUCT(Code),
CONSTRAINT change_admin_fk FOREIGN KEY(AdministratorID) REFERENCES ADMINS(Password)
);

CREATE TABLE PREFERENCES(
UserCode VARCHAR(20) NOT NULL,
CategoryID INT NOT NULL,
CodeOfProduct INT NOT NULL, 
CONSTRAINT preference_user_fk FOREIGN KEY(UserCode) REFERENCES USERS(Password),
CONSTRAINT preference_category_fk FOREIGN KEY(CategoryID) REFERENCES CATEGORY(Password),
CONSTRAINT preference_product_fk FOREIGN KEY(CodeOfProduct) REFERENCES PRODUCT(Code)
);

CREATE TABLE OFFER(
OfferID INT NOT NULL,
CodeOfProduct INT NOT NULL,
DiscountValue INT NOT NULL,
NewPrice DOUBLE(6,2) NOT NULL,
Description VARCHAR(500) NOT NULL,
CONSTRAINT offer_pk PRIMARY KEY (OfferID),
CONSTRAINT offer_product_fk FOREIGN KEY(CodeOfProduct) REFERENCES PRODUCT(Code)
);

